### ISSUE TITLE
Disable logging

### ISSUE THREAD

**Issue by themetalfleece** [vordgi/nimpl-middleware-chain#24]
Thanks for this package! It has helped me with react-intl and authjs (I saw your message on StackOverflow).

Is it possible to add an option to disable logging? There's lots of logs like `Changing destination between middlewares: http://localhost:3000/en (none) -> http://localhost:3000/en (rewrite)`. This won't be ideal when I release my app.

Thanks in advance!

**Comment by vordgi** [comment]
Hello! Thanks for the issue, I'll add the new option soon!

**Comment by vordgi** [comment]
Shipped in v0.4.0

Documentation - https://nimpl.tech/middleware-chain#custom-logger

**Comment by themetalfleece** [comment]
Wow that was very fast! And the docs are beautiful, thanks for the amazing work 🙌

**Comment by vordgi** [comment]
I greatly value those who describe issues and I try to solve all problems as quickly as possible. So thank you once again for sharing!)
